### ISSUE TITLE
Remove components

### ISSUE THREAD

**Issue by BryceRussell** [BryceRussell/astro-headless-ui#8]
These components were created a long time ago and a lot of them are poorly designed. All components that use scripts or styles should be removed (for now). That basically means everything goes except [the components inside this section](https://github.com/BryceRussell/astro-headless-ui/wiki#component)

In the future, these components can be revisited (like the theme components)

1. Remove these folders: 

```
package
  client-components
  style-components
  scripts
```
2. Update package `exports`
3. Remove all other references to these components

**Comment by astriskit** [comment]
@BryceRussell - shouldn't #10 close this issue?

**Comment by BryceRussell** [comment]
Yes, thanks!
